# Generated by Django 6.0.3 on 2026-04-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_appointment_veterinarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
